### ISSUE TITLE
No value has been specified for property mainClassName 

### ISSUE THREAD

**Issue by nogo** [johnrengelman/shadow#336]
Please check the (User Guide)[http://imperceptiblethoughts.com/shadow] before submitting "how do I do 'x'?" questions!

### Shadow Version
2.0.1

### Gradle Version
4.3

### Expected Behavior
work as in 4.2.1

### Actual Behavior
:shadowJar
A problem was found with the configuration of task ':shadowJar'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.
 - No value has been specified for property 'mainClassName'.

### Build script

Extract of my build script

apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'com.github.johnrengelman.shadow'

mainClassName = 'com.package.to.Class'

shadowJar {
  baseName = 'launcher'
  classifier = null
  version = null
}

**Comment by andrii-kovalenko-ct** [comment]
same here

**Comment by sdeleuze** [comment]
Same here with Gradle 4.3

**Comment by napstr** [comment]
Fwiw the resulting jar still works (for me) despite the warning, what actually breaks with gradle 4.3 is `runShadow`.

**Comment by lbergelson** [comment]
I'm also seeing this with shadow 2.0.2 and gradle 4.4.

**Comment by sgnewson** [comment]
Might just be a missing `mainClassName = 'com.package.to.Class'` in this plugin's build?

**Comment by jonwagner** [comment]
If you define `mainClassName` before you apply the plugin, the build succeeds. Sounds like an issue with initialization order.

**Comment by sgnewson** [comment]
Can confirm, placing the mainClassName after the application plugin and before the shadow plugin lines removes the warnings

**Comment by Mat2095** [comment]
I'm also seeing this with shadow 2.0.2 and gradle 4.5.

**Comment by johnrengelman** [comment]
yeah, i need to improve this, but the workaround is to specify `mainClassName` before applying the Shadow plugin.

**Comment by RaviH** [comment]
With the build.gradle below, I still get ` - No value has been specified for property 'mainClassName'.
`
```
plugins {
    id 'application'
    id 'com.github.johnrengelman.shadow' version '2.0.1'
}

mainClassName = 'io.vertx.core.Launcher'
def vertxVersion = '3.5.0'
def mainVerticleName = 'com.charter.devtool.web.vertx.verticle.MainVerticle'
def watchForChange = 'src/**/*'
def doOnChange = './gradlew classes'

dependencies {
    compile project(':devtool-core')
    compile project(':devtool-db')
    compile project(':devtool-stash-client')

    compile('io.vertx:vertx-core:3.5.0')
    compile('io.vertx:vertx-web:3.5.0')
    compile('com.zandero:rest.vertx:0.7.5')
    compile('org.eclipse.jgit:org.eclipse.jgit:4.9.2.201712150930-r')
    compile('com.github.salomonbrys.kodein:kodein:4.1.0')
}

shadowJar {
    mainClassName = 'io.vertx.core.Launcher'
    classifier = 'fat'
    manifest {
        attributes "Main-Verticle": mainVerticleName
    }
    mergeServiceFiles {
        include 'META-INF/services/io.vertx.core.spi.VerticleFactory'
    }
}

run {
    args = ['run', mainVerticleName, "--redeploy=$watchForChange", "--launcher-class=$mainClassName", "--on-redeploy=$doOnChange"]
}
```

**Comment by Mat2095** [comment]
Try something like
```groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.2'
    }
}

plugins {
    id "application"
}

mainClassName = '...'

apply plugin: 'com.github.johnrengelman.shadow'

[...]
```

**Comment by ljohnston** [comment]
The above workaround fixes the 'mainClassName' issue, but does not address the following warning:

> Task :vertx-web:startShadowScripts 
Using TaskInputs.file() with something that doesn't resolve to a File object has been deprecated and is scheduled to be removed in Gradle 5.0. Use TaskInputs.files() instead.

**Comment by ljohnston** [comment]
After a little more digging, seems like this has been fixed but not yet released. Thx @johnrengelman ! Looking forward to 2.0.3.

**Comment by koralgooll** [comment]
The application needs this property in gradle build file. It is in docs.

**Comment by hpmtissera** [comment]
Looks like issue is fixed in Version 2.0.4

**Comment by Mat2095** [comment]
I'm still getting the error with version 2.0.4.

**Comment by maikelsteneker** [comment]
The problem is still there for me when using 2.0.4 as well.

**Comment by black-snow** [comment]
Moving `mainClassName` before applying the plugin doesn't help for me.

**Comment by takirala** [comment]
This is still a problem with gradle `4.10` and shadow `2.0.4`.

**Comment by sora4222** [comment]
For those that are having a struggle in Intellij and their Gradle build, please check your gradle build in gradle/wrapper/graddle-wrapper.jar
I was having this issue until I changed my gradle version to 4.9, I actually did this by just changing the referenced gradle file to */gradle-4.9-bin.zip. 4.9 solved it for me.

**Comment by takirala** [comment]
@sora4222 When you say `solved` do you mean that the warning no longer appears or were you able to compile the code ?

I am using gradle `4.10` and the warning still appears for me with `2.0.4`

**Comment by sasconsul** [comment]
I have the problem with shadow plugin version 4.0.3, dropping back to 4.0.2 works.

**Comment by cxyzy1** [comment]
update to shadow plugin version 5.0.0

**Comment by lUNuXl** [comment]
```
buildscript {
    repositories {
        jcenter()
    }
    
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.4'
    }
}

apply plugin: 'com.github.johnrengelman.shadow'
apply plugin: 'kotlin'
apply plugin: 'application'

mainClassName = "io.ktor.server.jetty.EngineMain"
group 'pl.smiesznadomena'
version '0.0.2'


sourceSets {
    main.kotlin.srcDirs = main.java.srcDirs = ['src']
    test.kotlin.srcDirs = test.java.srcDirs = ['test']
    main.resources.srcDirs = ['resources']
    test.resources.srcDirs = ['testresources']
}

repositories {
    mavenLocal()
    jcenter()
    maven { url 'https://kotlin.bintray.com/ktor' }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "io.ktor:ktor-server-jetty:$ktor_version"
    implementation "ch.qos.logback:logback-classic:$logback_version"
    implementation "io.ktor:ktor-server-core:$ktor_version"
    implementation "io.ktor:ktor-server-host-common:$ktor_version"
    implementation "io.ktor:ktor-locations:$ktor_version"
    testImplementation "io.ktor:ktor-server-tests:$ktor_version"
    implementation 'net.dv8tion:JDA:4.1.1_133'
}

// This task will generate your fat JAR and put it in the ./build/libs/ directory
shadowJar {
    manifest {
        attributes 'Main-Class': mainClassName
    }
}

```

```
A problem was found with the configuration of task ':shadowJar'.
> No value has been specified for property 'mainClassName'.
```

**Comment by jsonwan** [comment]
I have the problem with shadow plugin version 2.0.2 and gradle version 6.1.0, upgrade shadow plugin to 5.1.0 works.

**Comment by marklapasa** [comment]
Able to reproduce this same problem with Gradle 6.5

**Comment by eric-ampire** [comment]
I have the same problem but I solved it by updating Gradle to version 6.1.1 and I also updated the version of shadow `classpath "com.github.jengelman.gradle.plugins:shadow:6.0.0".`

**Comment by red-avtovo** [comment]
In order to fix the issue you need to add the following block: 
```
application {
	// Desired way mainClass.set(MAIN_CLASS) causes an issue during jar packaging
	@Suppress("DEPRECATION")
	mainClassName = MAIN_CLASS
}
```

**Comment by knyttl** [comment]
```
        // Desired way mainClass.set("<main class>") causes an issue during jar packaging
	@Suppress("DEPRECATION")
	mainClassName ="<your main class here>"
```

This is not a solution - the mainClassName should not be used anymore, so the shadow plugin should not use it.

**Comment by joffrey-bion** [comment]
@knyttl for this reason I believe the issue should be reopened. This is a bug in the shadow plugin, using a deprecated API, and it should be fixed.

I'm surprised on Gradle side, though, that calling `mainClass.set("...")` doesn't also set `mainClassName` for backwards compat.

**Comment by pmorch** [comment]
This solution doesn't work with gradle 6.7 and shadowJar 6.1.0:

```kotlin
application {
	// Desired way mainClass.set("<main class>") causes an issue during jar packaging
	@Suppress("DEPRECATION")
	mainClassName ="<your main class here>"
}
```

It removes the strikethrough formatting from Intellij, but `./gradlew shadowJar` still reports:

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
```

And it [sounds like](https://discuss.gradle.org/t/how-to-suppress-gradle-deprecation-warnings/24198) suppression of warnings from gradle is not possible by choice...

**Comment by jspetrak** [comment]
> This solution doesn't work with gradle 6.7 and shadowJar 6.1.0:
> 
> And it [sounds like](https://discuss.gradle.org/t/how-to-suppress-gradle-deprecation-warnings/24198) suppression of warnings from gradle is not possible by choice...

I have just had the same issue on Gradle 7.0 and ShadowJar 6.1.0... After `gradle clean build shadowJar` the error did not occur.
